CREATE DATABASE [HOSPITAL]
USE [HOSPITAL]
GO
CREATE TABLE [PATIENT](
[Id]				INT PRIMARY KEY IDENTITY(0,1)		NOT NULL,
[Fullname]			NVARCHAR(30)						NOT NULL,
[Dateofbirth]		DATETIME							NOT NULL,
[Status]			NVARCHAR(20)						NOT NULL,
[Position]			NVARCHAR(20)						NOT NULL
)
GO
CREATE TABLE [DOCTOR](
[Id]				INT PRIMARY KEY IDENTITY(0,1)		NOT NULL,
[Doctorname]		NVARCHAR(30)						NOT NULL,
[Post]				NVARCHAR(20)						NOT NULL,
[Skill]				NVARCHAR(20)						NOT NULL,
[Specialization]	NVARCHAR(20)						NOT NULL
)
GO
CREATE TABLE [THERAPY](
[Id]				INT PRIMARY KEY IDENTITY(0,1)		NOT NULL,
[Diagnose]			NVARCHAR(30)						NOT NULL,
[Ambulatory]		NVARCHAR(10)						NOT NULL,
[Disability]		INT									NOT NULL,
[Begintherapy]		DATETIME							NOT NULL,
[Idpatient]			INT CONSTRAINT FK_THERAPY_IDPATIENT_PATIENT_ID FOREIGN KEY REFERENCES [PATIENT] ([ID]) NOT NULL,
[Iddoctor]			INT CONSTRAINT FK_THERAPY_IDDOCTOR_DOCTOR_ID FOREIGN KEY REFERENCES [DOCTOR] ([ID]) NOT NULL
)
GO